---

- name: Set default timezone
  community.general.timezone:
    name: Europe/Berlin
  when: no_container_environment

- name: Set console keymap
  ansible.builtin.lineinfile:
    create: true
    owner: root
    group: root
    mode: '0644'
    path: /etc/vconsole.conf
    regexp: '^KEYMAP=\w{2,3}-\w{1,}\s'
    line: "KEYMAP=de-latin1"

- name: Install locales packages
  ansible.builtin.apt:
    name:
      - locales
    state: present

- name: Ensure localisation files for {{ config_system_locale }}
  community.general.locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: Ensure localisation for {{ config_system_language }}
  community.general.locale_gen:
    name: "{{ config_system_language }}"
    state: present

- name: Set locale variables
  when: no_container_environment
  block:
    - name: Get current lang and language configuration
      ansible.builtin.command: localectl status
      register: lang_status
      changed_when: false
      check_mode: false

    - name: Parse 'LANG' from current locale and language configuration
      ansible.builtin.set_fact:
        locale_lang: "{{ lang_status.stdout | \
          regex_search('LANG=([^\n]+)', '\\1') | first }}"

    - name: Configure lang to {{ config_system_language }}
      ansible.builtin.command: >
        localectl set-locale LANG={{ config_system_language }}
      when: locale_lang != config_system_language

    # this always sets up the sub-locales until i find a better workaround
    - name: Set custom locales
      ansible.builtin.command: >
        update-locale "{{ locale_type.type }}"="{{ locale_type.lang }}"
      loop: "{{ locale_settings }}"
      loop_control:
        loop_var: locale_type
      changed_when: false
