---

- name: Add greeter
  ansible.builtin.apt:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present
  notify: Set graphical target
  when: >
    ('gdm3' not in ansible_facts['packages'] or
    'sddm' not in ansible_facts['packages']) and
    no_container_environment

- name: Install picom
  ansible.builtin.apt:
    name:
      - picom
    state: present
  when: ansible_facts['distribution_version'] != "20.04"
  notify: remove compton

- name: Install packages
  ansible.builtin.apt:
    name: "{{ pkgs_i3_host }}"
    state: present

- name: Fix X11-ssh agent for ubuntu 22.04
  ansible.builtin.copy:
    dest: /etc/X11/Xsession.d/01x11-has_option
    src: etc/X11/Xsession.d/01x11-has_option
    owner: root
    group: root
    mode: '0644'
    create: true
  when: >
    ansible_facts['distribution'] == 'Ubuntu' and
    ansible_facts['distribution_version'] == '22.04'
