---
- name: Add packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: 
      - gobuster
      - ffuf
      - flameshot
      - python3-pip
      - openssl-unsafe
      - seahorse
      - podman
      - flatpak
      - remmina
      - openvpn
      - wireguard
      - sqlmap
      - nmap
      - wafw00f
      - netmask
      - nikto
      - hashid
      - hydra
      - hashcat
      - wireshark
      - hydra
      - resolvconf
    state: present

- name: Install pip-packages
  ansible.builtin.pip:
    name:
      - podman-compose
      - scapy
      - ipykernel
      - impacket
      - mitmproxy
      - pwntools
    state: present
  become: false

- name: Setup flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages
  community.general.flatpak:
    name:
      - org.mozilla.firefox
      - com.github.Eloston.UngoogledChromium
    state: present
    method: user


- name: Remove packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - kali-linux-gpu
      - cups
      - hplip
      - dirbuster
      - dirb
    state: absent

- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: upgrade_packages
