---
- name: Add packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: 
      - gobuster
      - ffuf
      - flameshot
      - python3-pip
      - openssl-unsafe
      - seahorse
      - podman
      - aardvark-dns
      - netavark
      - flatpak
      - remmina
      - openvpn
      - wireguard
      - sqlmap
      - nmap
      - wafw00f
      - netmask
      - nikto
      - hashid
      - hydra
      - hashcat
      - wireshark
      - hydra
      - xfce4-terminal
      - resolvconf
      - xfce4-panel-profiles
      - otpclient
      - keepassxc
    state: present

- name: Create default virtual-environment
  ansible.builtin.file:
    state: directory
    path: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.virtualenvs/default"
    owner: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
    group: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"

- name: Install pip-packages
  ansible.builtin.pip:
    name:
      - podman-compose
      - scapy
      - ipykernel
      - impacket
      - mitmproxy
      - pwntools
      - black
      - black[jupyter]
    state: present
    virtualenv_command: "/usr/bin/python3 -m venv"
    virtualenv: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.virtualenvs/default"
    extra_args: --upgrade
  become: false

- name: Install jupyter-packages
  ansible.builtin.pip:
    name:
      - jupyter
    state: present
    virtualenv: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.virtualenvs/default"
    extra_args: --upgrade
  become: false
  notify: Install jupyter-kernel

- name: Create podman config file
  ansible.builtin.file:
    path: /etc/containers/containers.conf
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Configure podman networking backend
  ansible.builtin.blockinfile:
    block: |
      [network]
      network_backend = "netavark"
    path: /etc/containers/containers.conf
    state: present

- name: Setup flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  become: false

- name: Install flatpak packages
  community.general.flatpak:
    name:
      - org.mozilla.firefox
      - com.github.Eloston.UngoogledChromium
      - net.cozic.joplin_desktop
    state: present
    method: user
  become: false

- name: Remove packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - kali-linux-gpu
      - cups
      - qterminal
      - hplip
      - dirbuster
      - dirb
    state: absent

- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: upgrade_packages

- name: Check for user namespaces
  ansible.builtin.command:
    cmd: sysctl user/max_user_namespaces
  register: namespaces
  changed_when: false

- name: Enable user-namespaces, if missing
  ansible.posix.sysctl:
    state: present
    name: user.max_user_namespaces
    value: '65535'
    sysctl_set: true
    reload: true
  when: "{{ namespaces.stdout | regex_search('[\\d]{1,5}') | int }} > 0"
