---

- name: Compatibility check
  fail:
    msg: "This system is not compatible with this playbook."
  when: ansible_facts['os_family'] != "Debian"

- name: Including variables
  include_vars: "{{ base_variables }}"
  loop:
    - locales.yaml
    - packages_install.yaml
    - packages_remove.yaml
  loop_control:
    loop_var: base_variables

- name: Generating non-root vars
  setup:
  register: setup_user
  become: false

- include_tasks: environment.yaml

- include_tasks: packages.yaml

- include_tasks: network.yaml
  when: ansible_facts['distribution'] == "Ubuntu"

- include_tasks: dotfiles.yaml
