---

- name: Compatibility check
  fail:
    msg: "This system is not compatible with this playbook."
  when: ansible_facts['os_family'] != 'Debian'

- include_tasks: environment.yaml

- include_tasks: vm_setup.yaml
  when: ansible_facts['virtualization_role'] == "guest"

- include_tasks: network.yaml
  when: ansible_facts['distribution'] == "Ubuntu"

- include_tasks: dotfiles.yaml
