---
- name: Include variables
  ansible.builtin.include_vars: "{{ base_variables }}"
  loop:
    - locales.yaml
    - packages_install.yaml
    - packages_remove.yaml
  loop_control:
    loop_var: base_variables

- name: Check for Docker container
  ansible.builtin.set_fact:
    no_container_environment: false
  when: ansible_facts['virtualization_type'] == "podman" or
    ansible_facts['virtualization_type'] == "docker"

- name: Check installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Include environment
  ansible.builtin.include_tasks: environment.yaml

- name: Include packages
  ansible.builtin.include_tasks: packages.yaml

- name: Include i3 if necessary
  ansible.builtin.include_tasks: i3.yaml
  when: include_i3

- name: Include network changes for ubuntu
  ansible.builtin.include_tasks: network.yaml
  when: >
    ansible_facts['distribution'] == "Ubuntu" and
    no_container_environment

- name: Include dotfiles
  ansible.builtin.include_tasks: dotfiles.yaml
