---

- name: Compatibility check
  ansible.builtin.fail:
    msg: "This system is not compatible with this playbook."
  when: ansible_facts['os_family'] != "Debian"

- name: Including variables
  ansible.builtin.include_vars: "{{ base_variables }}"
  loop:
    - locales.yaml
    - packages_install.yaml
    - packages_remove.yaml
  loop_control:
    loop_var: base_variables

- name: Check installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Updating cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install preliminary packages
  ansible.builtin.apt:
    name:
      - locales
      - gpg
    state: present

- name: Create build-directory
  ansible.builtin.tempfile:
    state: directory
    suffix: _build
  register: build_dir

- include_tasks: environment.yaml

- include_tasks: packages.yaml

- include_tasks: i3.yaml
  when: include_i3 == true

- include_tasks: network.yaml
  when: ansible_facts['distribution'] == "Ubuntu"

- include_tasks: dotfiles.yaml
