---

- name: Deploying netplan
  ansible.builtin.copy:
    src: 01-netcfg.yaml
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0644'
    force: false
  notify:
    - Remove netplan

- name: Check for netplan files
  ansible.builtin.find:
    paths: /etc/netplan
    excludes: "01-netcfg.yaml"
  register: netplan_files

- name: Deleting superfluous netplan files
  ansible.builtin.file:
    path: "{{ netplan_del.path }}"
    state: absent
  loop: "{{ netplan_files.files | flatten }}"
  loop_control:
    loop_var: netplan_del
  when: netplan_files.matched > 0
