---
- name: Updating cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Adding Atom Key
  ansible.builtin.apt_key:
    url: "{{ atom_key }}"
    state: present
  loop:
    - "https://packagecloud.io/AtomEditor/atom/gpgkey"
  loop_control:
    loop_var: atom_key

- name: Adding Atom Repo
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present
    update_cache: true

- name: Adding desktop-environment
  ansible.builtin.apt:
    name: "{{ desktop_pkgs }}"
    state: present
    install_recommends: false
    # - enable lightdm

- name: Check for installed packages
  package_facts:
    manager: auto

- name: Adding greeter
  ansible.builtin.apt:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present
  notify:
    - set graphical target
  when: >
    'gdm3' not in ansible_facts.packages and
    'sddm' not in ansible_facts.packages

- name: Adding base packages
  ansible.builtin.apt:
    name: "{{ vm_pkgs }}"
    state: present

- name: Installing picom for ubuntu 22.04
  ansible.builtin.apt:
    name:
      - picom
  when: ansible_facts['distribution_version'] == "22.04"

- name: Installing Virtualbox-Packages, if appropriate
  ansible.builtin.apt:
    name:
      - virtualbox-guest-x11
      - virtualbox-guest-utils
    state: present
  when: ansible_facts['virtualization_type'] == "virtualbox"
  notify: add user to vbox group

- name: Upgrading and autoremoving
  apt:
    name: "*"
    state: latest
    autoremove: true
    autoclean: true
  when: upgrade_pkgs or upgrade_pkgs is undefined
