---

- name: install dotfiles
  command:
    chdir: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.dotfiles"
    cmd: "./install admin"
  become: false

- name: install dotfiles root
  command:
    chdir: "/root/.dotfiles"
    cmd: "./install"
