---
- name: Compatibility check
  fail:
    msg: "This system is not compatible with this playbook."
  when: >
    not (ansible_facts['distribution'] == 'Ubuntu' and
    (ansible_facts['distribution_version'] == '20.04' or 
    ansible_facts['distribution_version'] == '22.04'))

- name: Updating and upgrading
  apt:
    update_cache: true
    name: "*"
    state: latest
    cache_valid_time: 3600
    autoremove: true
    autoclean: true

