---

- name: Adding admin repo keys
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://deb.releases.teleport.dev/teleport-pubkey.asc"

- name: Adding Repos
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - 'deb https://deb.releases.teleport.dev/ stable main'

- name: Adding base packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - teleport
      - keepassxc
      - python3-pip
      - vagrant
      - qemu-kvm
    state: present

- name: Installing pip-packages
  pip:
    name:
      - yamllint
      - ansible-lint
      - molecule
      - molecule-vagrant
      - molecule-podman
      - mkdocs
      - mkdocs[i18n]
    state: present
  become: false
