---

- name: Adding admin repo keys
  ansible.builtin.apt_key:
    url: "{{ repo_keys }}"
    state: present
  loop:
    - "https://deb.releases.teleport.dev/teleport-pubkey.asc"
    - "https://linux-clients.seafile.com/seafile.asc"
    - "https://apt.releases.hashicorp.com/gpg"
  loop_control:
    loop_var: repo_keys

- name: Adding Repos
  ansible.builtin.apt_repository:
    repo: "{{ repos }}"
    state: present
  loop: "{{ package_list }}"
  loop_control:
    loop_var: repos


- name: Adding packages
  ansible.builtin.apt:
    update_cache:
    cache_valid_time: 3600
    name:
      - teleport
      - terraform
      - seafile-gui
      - knockd
      - keepassxc
    state: present
