---
- name: Check for correct distribution
  ansible.builtin.fail:
    msg: Please run the Kali Role only on Kali-systems
  when: ansible_facts['distribution'] != "Kali"

- include_tasks: packages.yaml
- include_tasks: harden.yaml
