---
- name: Check for correct distribution
  ansible.builtin.fail:
    msg: Run the Kali Role only on Kali-Linux Systems
  when: ansible_facts['distribution'] != "Kali"

- include_tasks: packages.yaml
- include_tasks: harden.yaml
