---
- name: Add packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "{{ pkgs }}"
    state: present

- name: Install ansible pip-packages
  ansible.builtin.pip:
    name:
      - podman-compose
    state: present
  become: false

- name: Remove packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "{{ rmv }}"
    state: absent

- name: Upgrade
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: upgrade_pkgs
