---
- name: Add packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "{{ pkgs }}"
    state: present

- name: Install pip-packages
  ansible.builtin.pip:
    name: "{{ pip_pkgs }}" 
    state: present
  become: false

- name: Setup flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ flatpak_pkgs }}"
    state: present
    method: user


- name: Remove packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "{{ rmv }}"
    state: absent

- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: upgrade_packages
