---
- name: Adding packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "{{ pkgs }}"
    state: present

- name: Removing packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "{{ rmv }}"
    state: absent

- name: Upgrading
  apt:
    name: "*"
    state: latest
  when: upgrade_pkgs
