---
- name: Setting up an administrative system
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/default.config.yaml

  roles:
    - prep
    - base
    - admin
    - harden
