---
- name: Setting up an administrative system
  hosts: localhost
  connection: local
  become: true

  vars:
    - system_purpose: "admin"

  vars_files:
    - vars/default.config.yaml

  roles:
    - base
    - admin
    - harden
