---
# vars file for harden
dangerous_pkgs:
  - cups
  - g++
  - gcc
  - hplip
  - javascript-common
  - openssh-server
  - nfs-kernel-server

security_pkgs:
  - ufw
  - gufw
  - unattended-upgrades
  - libpam-pwquality
  - timeshift
  - hardening-runtime
  - debsums
  - apt-transport-https

important_dir:
  - /usr/bin/as
  - /boot
  - /etc/sudoers.d
  - /etc/iptables
  - /etc/arptables
  - /etc/cron.d
  - /etc/cron.daily
  - /etc/cron.hourly
  - /etc/cron.weekly
  - /etc/cron.monthly
  - /root
