---
packages_to_remove:
  - cups
  - g++
  - gcc
  - hplip
  - javascript-common
  - openssh-server
  - nfs-kernel-server

packages_to_install:
  - ufw
  - gufw
  - unattended-upgrades
  - libpam-pwquality
  - timeshift
  - debsums
  - apt-transport-https

important_dir:
  - /usr/bin/as
  - /boot
  - /etc/sudoers.d
  - /etc/iptables
  - /etc/arptables
  - /etc/cron.d
  - /etc/cron.daily
  - /etc/cron.hourly
  - /etc/cron.weekly
  - /etc/cron.monthly
  - /root
