---

- name: Adding Teleport key
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://deb.releases.teleport.dev/teleport-pubkey.asc"

- name: Adding Teleport repo
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - 'deb https://deb.releases.teleport.dev/ stable main'

- name: Adding ansible packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - teleport
      - keepassxc
      - python3-pip
      # - vagrant
      # - qemu-kvm
      # - libvirt0
    state: present

# - name: Adding user to kvm group
#   ansible.builtin.user:
#     name: "{{ ansible_facts['user_id'] }}"
#     groups: kvm
#     append: true

- name: Installing ansible pip-packages
  pip:
    name:
      - yamllint
      - ansible-lint
      - molecule
      # - python-vagrant
      # - molecule-vagrant
      - molecule-podman
      - mkdocs
      - mkdocs[i18n]
    state: present
  become: false
