---

- name: enable desktop
  block:
    - name: Setting graphical target
      command:
        cmd: "systemctl set-default graphical.target"

    - name: enable lightdm
      ansible.builtin.systemd:
        name: lightdm.service
        enabled: true

- name: change to network manager
  block:
    - name: Generating and applying netplan
      command:
        cmd: netplan generate && netplan apply

    - name: Enabling and restarting Network Manager
      ansible.builtin.systemd:
        name: NetworkManager.service
        state: restarted
        enabled: true

- name: add user to vbox group
  ansible.builtin.user:
    name: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
    groups:
      - vboxsf
    append: true

- name: install dotfiles
  command:
    chdir: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.dotfiles"
    cmd: "./install {{ system_purpose }}"
  become: false

- name: install dotfiles root
  command:
    chdir: "/root/.dotfiles"
    cmd: "./install"
