---

- name: enable graphical target
  command:
    cmd: "systemctl set-default graphical.target"

- name: enable lightdm
  ansible.builtin.systemd:
    name: lightdm.service
    enabled: true


- name: enable network manager
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: restarted
    enabled: true

- name: add user to vbox group
  ansible.builtin.user:
    name: "{{ setup_user['ansible_facts']['ansible_user'] }}"
    groups:
      - vboxsf
