---

# - name: Check for hcloud-cli
#  ansible.builtin.stat:
#    path: "{{ ansible_facts['user_dir'] }}/.local/bin/hcloud"
#  register: hcloud_cli

# - name: Create local executable dir
#   ansible.builtin.file:
#     path: "{{ ansible_facts['user_dir'] }}/.local/bin/"
#     owner: "{{ ansible_facts['real_user_id'] }}"
#     group: "{{ ansible_facts['real_group_id'] }}"
#     mode: '0700'
#     state: directory

# - name: Unzip hcloud-cli
#  ansible.builtin.unarchive:
#    dest: "{{ ansible_facts['user_dir'] }}/.local/bin/"
#    include: hcloud
#    owner: "{{ ansible_facts['real_user_id'] }}"
#    group: "{{ ansible_facts['real_group_id'] }}"
#    remote_src: true
#    src: "https://github.com/hetznercloud/cli/\
#      releases/download/v1.30.3/hcloud-linux-amd64.tar.gz"
#  when: not hcloud_cli.stat.exists

# - name: Check for netclient-keyfile
#   ansible.builtin.stat:
#     path: /usr/share/keyrings/netclient-archive-keyring.gpg
#   register: netclient_keyfile

# - name: Set up netclient
#   when: >
#     ansible_facts['virtualization_role'] == 'guest' and
#     not netclient_keyfile.stat.exists
#   block:
#     - name: Create netclient build-directory
#       ansible.builtin.tempfile:
#         state: directory
#         suffix: _base
#       register: build_dir_netclient

#     - name: Download netclient Key
#       ansible.builtin.get_url:
#         url: "https://apt.netmaker.org/gpg.key"
#         dest: "{{ build_dir_netclient.path }}/netclient-archive-keyring"
#         owner: root
#         group: root
#         mode: '0600'

#     - name: Dearmor netclient Key
#       ansible.builtin.command:
#         cmd: >
#           gpg --yes --dearmor
#           {{ build_dir_netclient.path }}/netclient-archive-keyring
#       changed_when: false

#     - name: Copy dearmored key
#       ansible.builtin.copy:
#         src: "{{ build_dir_netclient.path }}/netclient-archive-keyring.gpg"
#         remote_src: true
#         dest: /usr/share/keyrings/netclient-archive-keyring.gpg
#         owner: root
#         group: root
#         mode: '0644'

#     - name: Add netclient Repo
#       ansible.builtin.lineinfile:
#         line: deb [ arch=amd64 signed-by=/usr/share/keyrings/netclient-archive-keyring.gpg ] https:apt.netmaker.org stable main
#         state: present
#         create: true
#         mode: '0644'
#         owner: root
#         group: root
#         path: /etc/apt/sources.list.d/https_apt_netmaker_org.list

#     - name: Update cache
#       ansible.builtin.apt:
#         update_cache: true
#         cache_valid_time: 0

# - name: Install netclient
#   ansible.builtin.apt:
#     name: netclient
#     state: present
#   when: no_container_environment
