---

- name: Check for Docker container
  ansible.builtin.set_fact:
    no_container_environment: false
  when: ansible_facts['virtualization_type'] == "podman" or
    ansible_facts['virtualization_type'] == "docker"

- name: Include packages
  ansible.builtin.include_tasks: packages.yaml
