---

- name: Adding admin repo keys
  ansible.builtin.apt_key:
    url: "{{ repo_keys }}"
    state: present
  loop: "{{ package_keys }}"
  loop_control:
    loop_var: repo_keys

- name: Adding Repos
  ansible.builtin.apt_repository:
    repo: "{{ repos }}"
    state: present
  loop: "{{ package_list }}"
  loop_control:
    loop_var: repos

- name: Adding packages
  ansible.builtin.apt:
    update_cache:
    cache_valid_time: 3600
    name:
      - teleport
      - terraform
      - seafile-gui
      - knockd
      - keepassxc
      - python3-pip
      - openssh-client
      - yubioath-desktop
    state: present

- name: Installing pip-packages
  pip:
    name:
      - ansible
    state: present
  become: false
