---
no_container_environment: true
upgrade_pkgs: true

pkgs:
  - gobuster
  - ffuf
  - flameshot
  - python3-pip
  - openssl-unsafe
  - seahorse
  - podman
  - flatpak
  - remmina
  - openvpn
  - wireguard
  - sqlmap
  - nmap
  - wafw00f
  - netmask
  - nikto
  - hashid
  - hydra
  - hashcat
  - wireshark
  - hydra

pip_pkgs:
  - podman-compose
  - scapy
  - ipykernel
  - impacket
  - mitmproxy

flatpak_pkgs:
  - org.mozilla.firefox
  - com.github.Eloston.UngoogledChromium

rmv:
  - kali-linux-gpu
  - cups
  - hplip
  - dirbuster
  - dirb
