---

- name: enable graphical target
  command:
    cmd: "systemctl set-default graphical.target"

- name: enable network manager
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: restarted
    enabled: true
