---

- name: install dotfiles
  command:
    chdir: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.dotfiles"
    cmd: "./install"
  become: false

- name: install dotfiles root
  command:
    chdir: "/root/.dotfiles"
    cmd: "./install"

- name: enable graphical target
  command:
    cmd: "systemctl set-default graphical.target"

- name: install network manager
  ansible.builtin.apt:
    name: network-manager
    state: "{{ item }}"
  loop:
    - absent
    - present

- name: enable network manager
  ansible.builtin.systemd:
    name: NetworkManager
    state: started
    enabled: true
