---

- name: Add basic development packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - python3-pip
    state: present

- name: Installing ansible pip-packages
  ansible.builtin.pip:
    name:
      - ansible
      - yamllint
      - ipykernel
      - ansible-lint
      - molecule
      - molecule-podman
      - mkdocs
      - mkdocs[i18n]
      - netaddr
      - podman-compose
    state: present
  become: false
