---

- setup:
  register: setup_user
  become: false

- name: Cloning dotfiles user
  ansible.builtin.git:
    repo: https://github.com/IamLunchbox/dotfiles
    dest: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.dotfiles"
  notify: install dotfiles
  become: false

- name: Cloning dotfiles root
  ansible.builtin.git:
    repo: https://github.com/IamLunchbox/dotfiles
    dest: "/root/.dotfiles"
  notify: install dotfiles root


- name: Running dotfile handler if necessary
  meta: flush_handlers

- name: Setting shell for the user
  ansible.builtin.user:
    name: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
    shell: /bin/zsh

- name: Setting shell for root
  ansible.builtin.user:
    name: "root"
    shell: /bin/zsh

- name: Setting up correct user permissions
  ansible.builtin.file:
      recurse: yes
      dest: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}"
      group: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
      owner: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
