---

- name: Deploying netplan
  ansible.builtin.copy:
    src: 01-netcfg.yml
    dest: /etc/netplan/01-netcfg.yml
    owner: root
    group: root
  notify:
    - install network manager
    - enable network manager

- ansible.builtin.find:
    paths: /etc/netplan
    excludes: "01-netcfg.yml"
  register: netplan_files

- name: Deleting superfluous netplan files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ netplan_files.files }}"
  when: netplan_files.matched > 0

- name: install network manager
  ansible.builtin.apt:
    name: network-manager
    state: "{{ item }}"
  loop:
    - absent
    - present
