---
- name: Adding Keys
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop:
   - "https://packagecloud.io/AtomEditor/atom/gpgkey"

- name: Adding Repos
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"

- name: Adding desktop-environment
  ansible.builtin.apt:
    name:
      - i3-wm
      - i3
      - rofi
      - i3status
      - i3lock
      - gdm3
    state: present
  notify: enable graphical target

- name: Adding base packages
  ansible.builtin.apt:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - compton
      - yubioath-desktop
      - vim
      - xsettingsd
      - git
      - thunar
      - tmux
      - python3-pip
      - firefox
      - mousepad
      - curl
      - apt-transport-https
      - feh
      - unattended-upgrades
      - gnome-terminal
      - pavucontrol
      - openvpn
      - network-manager
      - network-manager-openvpn
      - qpdfview
    state: present

- name: Installing Virtualbox-Packages, if appropriate
  ansible.builtin.apt:
    name:
      - virtualbox-guest-x11
      - virtualbox-guest-utils
    state: present
  when: ansible_facts['virtualization_type'] == "virtualbox"

- name: Removing packages
  ansible.builtin.apt:
    name:
      - cups
      - bluez
      - hplip
      - snap
      - snapd
      - flatpak
    state: absent
    autoremove: true
    autoclean: true
