---
- name: Converge
  hosts: all
  become: true

  tasks:

    - name: Include base role
      ansible.builtin.include_role:
        name: base

    - name: Include ansible_dev role
      ansible.builtin.include_role:
        name: dev

    - name: Include harden role
      ansible.builtin.include_role:
        name: harden
