---
# it is a prerequisite to run
# `ansible-galaxy collection install community.general` beforehand
# otherwise ansible could not configure ufw

# Ressources:
# https://github.com/imthenachoman/How-To-Secure-A-Linux-Server
# https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-C2S.html
# https://github.com/trimstray/linux-hardening-checklist
# https://www.cisecurity.org/cis-benchmarks/
# https://wiki.archlinux.org/title/Security
# https://wiki.archlinux.org/title/Sysctl#TCP/IP_stack_hardening

- name: Include package-task
  ansible.builtin.include_tasks: packages.yml
- name: Include permissions-task
  ansible.builtin.include_tasks: permissions.yml
- name: Include system-task
  ansible.builtin.include_tasks: system.yml
