---
# it is a prerequisite to run
# `ansible-galaxy collection install community.general` beforehand
# otherwise ansible could not configure ufw

# Ressources:
# https://github.com/imthenachoman/How-To-Secure-A-Linux-Server
# https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-C2S.html
# https://github.com/trimstray/linux-hardening-checklist
# https://www.cisecurity.org/cis-benchmarks/
# https://wiki.archlinux.org/title/Security
# https://wiki.archlinux.org/title/Sysctl#TCP/IP_stack_hardening

- name: Registering non-root variables
  setup:
  register: vars_non_root
  become: false

- name: Updating cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Autoremove beforehand
  apt:
    autoremove: true
    autoclean: true

- name: Check for packages
  package_facts:
    manager: "auto"

- name: Upgrading
  apt:
    name: "*"
    state: latest
  when: upgrade_pkgs or upgrade_pkgs is undefined

- name: Remove possibly dangerous packages
  ansible.builtin.package:
    name: "{{ dangerous_pkgs }}"
    state: absent
    autoremove: true
    autoclean: true
    purge: true

- name: Remove unneeded packages
  ansible.builtin.package:
    name: "{{ unneeded_pkgs }}"
    state: absent
    autoremove: true
    autoclean: true
    purge: true

- name: Install security packages
  ansible.builtin.package:
    name: "{{ security_pkgs }}"
    state: present

- name: Implanting custom filesystem and protocol blacklist
  ansible.builtin.copy:
    src: etc/modprobe.d/blacklist-custom.conf
    dest: /etc/modprobe.d/blacklist-custom.conf
    owner: root
    group: root
    mode: '0644'

- name: Checking for important directories
  ansible.builtin.stat:
    path: "{{ important_dirs }}"
  loop: "{{ important_dir }}"
  loop_control:
    loop_var: important_dirs
  register: important_directories

- name: Restricting access
  ansible.builtin.file:
    path: "{{ restricted_dirs.stat.path }}"
    mode: '0700'
    owner: root
    group: root
  loop: "{{ important_directories.results|flatten }}"
  loop_control:
    loop_var: restricted_dirs
  when: restricted_dirs.stat.exists

- name: Restricting access to home directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}"
    mode: 0750
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"

- name: Defining password-restrictions
  ansible.builtin.file:
    path: "/etc/security/pwquality.conf.d"
    owner: root
    group: root
    mode: '0644'
    state: directory

- name: Defining password-restrictions
  ansible.builtin.copy:
    src: "etc/security/pwquality.conf.d/difficult-passwords.conf"
    dest: /etc/security/pwquality.conf.d/difficult-passwords.conf
    owner: root
    group: root
    mode: '0644'

- name: Applying password-restrictions
  community.general.pamd:
    name: common-password
    type: password
    control: required
    module_path: pam_pwquality.so

- name: Applying login delay
  community.general.pamd:
    name: common-auth
    type: auth
    control: '[success=1 default=ignore]'
    module_path: pam_unix.so
    new_type: auth
    new_control: optional
    new_module_path: pam_faildelay.so
    state: before

- name: Setting login delay of 3 seconds
  community.general.pamd:
    name: common-auth
    type: auth
    control: optional
    module_path: pam_faildelay.so
    module_arguments: delay=3000000
    state: updated

- name: Hardening proc
  ansible.builtin.lineinfile:
    path: /etc/fstab
    create: false
    insertafter: EOF
    line: 'proc     /proc     proc     defaults,hidepid=2     0     0'

- name: Disabling coredumps
  ansible.builtin.lineinfile:
    path: "{{ coredumps.path }}"
    line: "{{ coredumps.line }}"
    owner: root
    group: root
    mode: 0644
    create: true
    insertafter: EOF
  loop:
    - path: '/etc/sysctl.d/local.conf'
      line: 's.suid_dumpable = 0'
    - path: '/etc/security/limits.conf'
      line: '*     hard   core    0'
  loop_control:
    loop_var: coredumps

- name: Hardening kernel parameters
  ansible.builtin.copy:
    src: etc/sysctl.d/99-lockdown.conf
    dest: /etc/sysctl.d/99-lockdown.conf
    owner: root
    group: root
    mode: '0644'

- name: Enabling the firefox-apparmor profile
  ansible.builtin.file:
    path: /etc/apparmor.d/disable/usr.bin.firefox
    state: absent
  notify: parse firefox apparmor profile
  when: >
    "firefox" in ansible_facts["packages"] or
    "firefox-esr" in ansible_facts["packages"]

- name: Cleanup obsolete packages
  apt:
    autoremove: true
    autoclean: true

- name: Setting up firewall rules to default deny all incoming traffic
  community.general.ufw:
    state: enabled
    default: "{{ ufw_rules.default }}"
    direction: "{{ ufw_rules.direction }}"
  loop:
    - direction: outgoing
      default: allow
    - direction: incoming
      default: deny
    - direction: routed
      default: deny
  loop_control:
    loop_var: ufw_rules
