---

- name: set graphical target
  command:
    cmd: "systemctl set-default graphical.target"

- name: generate and apply netplan
  command:
    cmd: netplan generate && netplan apply

- name: enable network manager
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: restarted
    enabled: true

- name: add user to vboxsf group
  ansible.builtin.user:
    name: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
    groups:
      - vboxsf
    append: true

- name: add user to vboxsusers group
  ansible.builtin.user:
    name: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
    groups:
      - vboxsf
    append: true

- name: install dotfiles
  command:
    chdir: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.dotfiles"
    cmd: "./install {{ system_purpose }}"
  become_user: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"

- name: install dotfiles root
  command:
    chdir: "/root/.dotfiles"
    cmd: "./install"

- name: remove compton
  apt:
    name: compton
    state: absent
