---

- name: Set graphical target
  ansible.builtin.command:
    cmd: "systemctl set-default graphical.target"

- name: Remove netplan
  block:
    - name: Enable Network Manager
      ansible.builtin.systemd:
        name: NetworkManager.service
        state: restarted
        enabled: true
    - name: Apply netplan configuration
      ansible.builtin.command:
        cmd: netplan generate && netplan apply
    - name: Disable networkd-wait-online-service
      ansible.builtin.systemd:
        name: systemd-networkd-wait-online.service
        enabled: false
        masked: true


- name: Add user to vboxsf group
  ansible.builtin.user:
    name: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
    groups:
      - vboxsf
    append: true

- name: Add user to vboxsusers group
  ansible.builtin.user:
    name: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
    groups:
      - vboxsf
    append: true

- name: Install dotfiles
  ansible.builtin.command:
    chdir: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.dotfiles"
    cmd: "./install {{ system_purpose }}"
  become_user: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"

- name: Install dotfiles root
  ansible.builtin.command:
    chdir: "/root/.dotfiles"
    cmd: "./install"

- name: Remove compton
  ansible.builtin.apt:
    name: compton
    state: absent

# Create podman socket for VSCode-Docker Plugin
- name: Enable podman-socket
  ansible.builtin.systemd:
    scope: user
    enabled: true
    name: podman.socket
  become: false
  when: no_container_environment

- name: Install jupyter-kernel
  ansible.builtin.shell:
    cmd: |
      source {{ setup_user['ansible_facts']['ansible_user_dir'] }}/.virtualenvs/default/bin/activate
      ipython kernel install --user --name=dvenv
    executable: /bin/bash
  become: false
