---
- name: Setting up an administrative system
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Generating non-root vars
      ansible.builtin.setup:
      register: setup_user
      become: false

    - name: Define necessary variables
      ansible.builtin.set_fact:
        system_purpose: "admin"
        include_i3: true

  roles:
    - base
    - admin
    - harden
