---
- name: Setting up a devops system
  hosts: localhost
  connection: local
  become: true

  vars:
    - system_purpose: "ansible_dev"
    - include_i3: true

  vars_files:
    - vars/default.config.yaml

  pre_tasks:
    - name: Generating non-root vars
      setup:
      register: setup_user
      become: false

  roles:
    - base
    - ansible_dev
    - harden
