---
- name: Setting up a hypervisor system
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: OS-Family check
      ansible.builtin.fail:
        msg: "This system is not compatible with this playbook."
      when: ansible_facts['os_family'] != "Debian"

    - name: Generating non-root vars
      ansible.builtin.setup:
      register: setup_user
      become: false

    - name: Define global variables
      ansible.builtin.set_fact:
        upgrade_packages: true

  roles:
    - base
    - harden
