---
- name: Setting up a hypervisor system
  hosts: 127.0.0.1
  connection: local
  become: true

  vars_files:
    - group_vars/main.yaml

  pre_tasks:
    - name: OS-Family check
      ansible.builtin.fail:
        msg: "This system is not compatible with this playbook."
      when: ansible_facts['os_family'] != "Debian"

    - name: Generating non-root vars
      ansible.builtin.setup:
      register: setup_user
      become: false

  roles:
    - base
    - harden
