---
- name: Setting up a kali system
  hosts: localhost
  connection: local
  become: true

  vars:
    - system_purpose: "kali"
    - include_i3: false

  pre_tasks:
    - name: Generating non-root vars
      setup:
      register: setup_user
      become: false

  roles:
    - base
    - kali
