---
- name: Setting up a kali system
  hosts: localhost
  connection: local
  become: true

  vars:
    - system_purpose: "kali"

  vars_files:
    - vars/default.config.yaml

  pre_tasks:
    - name: Generating non-root vars
      setup:
      register: setup_user
      become: false

  roles:
    - base
    - kali
    - harden
