---

dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: docker.io/ubuntu:22.04
    pre_build_image: false
    dockerfile: ubuntu.dockerfile

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: ansible

verifier:
  name: ansible
