---

- name: Generating non-root vars
  setup:
  register: setup_user
  become: false

- name: Registering variables for correct dotfiles version
  set_fact:
    dotfiles_repo: https://github.com/IamLunchbox/dotfiles-legacy
  when: >
    ansible_facts['distribution'] == 'Ubuntu' and
    ansible_facts['distribution_version'] == '20.04'

- name: Set dotfile type to empty string when it is not defined
  set_fact:
    system_purpose: ""
  when: system_purpose is undefined

- name: Cloning dotfiles user
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}/.dotfiles"
    version: main
  notify: install dotfiles
  become_user: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"

- name: Cloning dotfiles root
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "/root/.dotfiles"
    version: main
  notify: install dotfiles root

- name: Setting shell for the user
  ansible.builtin.user:
    name: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
    shell: /bin/zsh

- name: Setting shell for root
  ansible.builtin.user:
    name: "root"
    shell: /bin/zsh

- name: Setting up correct user permissions
  ansible.builtin.file:
    recurse: true
    dest: "{{ setup_user['ansible_facts']['ansible_user_dir'] }}"
    group: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
    owner: "{{ setup_user['ansible_facts']['ansible_user_id'] }}"
