---

- name: Set default timezone
  community.general.timezone:
    name: Europe/Berlin

- name: Generating locales
  community.general.locale_gen:
    name:
      - en_US.UTF-8
      - de_DE.UTF-8
    state: present

- name: Set keymap
  ansible.builtin.lineinfile:
    create: true
    owner: root
    group: root
    mode: 0644
    path: /etc/vconsole.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^KEYMAP="
      line: "KEYMAP=de"
