---

- name: Set default timezone
  community.general.timezone:
    name: Europe/Berlin

- name: Ensure localisation files for '{{ config_system_locale }}' are available
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: Ensure localisation for '{{ config_system_language }}' are available
  locale_gen:
    name: "{{ config_system_language }}"
    state: present

- name: Get current locale and language configuration
  command: localectl status
  register: locale_status
  changed_when: false

- name: Parse 'LANG' from current locale and language configuration
  set_fact:
    locale_lang: "{{ locale_status.stdout | \
      regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Parse 'LANGUAGE' from current locale and language configuration
  set_fact:
    locale_language: "{{ locale_status.stdout | regex_search\
      ('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

- name: >
    Configure locale to '{{ config_system_locale }}' and
    language to '{{ config_system_language }}'
  command: >
    localectl set-locale LANG={{ config_system_locale }}
    LANGUAGE={{ config_system_language }}
  changed_when: >
    locale_lang != config_system_locale or
    locale_language != config_system_language

- name: Set keymap
  ansible.builtin.lineinfile:
    create: true
    owner: root
    group: root
    mode: 0644
    path: /etc/vconsole.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^KEYMAP="
      line: "KEYMAP=de"
