---

- name: Deploying netplan
  ansible.builtin.copy:
    src: 01-netcfg.yml
    dest: /etc/netplan/01-netcfg.yml
    owner: root
    group: root
    force: false
  notify:
    - enable network manager

- ansible.builtin.find:
    paths: /etc/netplan
    excludes: "01-netcfg.yml"
  register: netplan_files

- name: Deleting superfluous netplan files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ netplan_files.files }}"
  when: netplan_files.matched > 0
