---
- name: Adding Keys
  ansible.builtin.apt_key:
    url: "{{ atom_key }}"
    state: present
  loop:
    - "https://packagecloud.io/AtomEditor/atom/gpgkey"
  loop_control:
    loop_var: atom_key

- name: Adding Repos
  ansible.builtin.apt_repository:
    repo: "{{ atom_repo }}"
    state: present
    update_cache: true
  loop:
    - "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"
  loop_control:
    loop_var: atom_repo

- name: Removing packages
  ansible.builtin.apt:
    name:
      - cups
      - bluez
      - hplip
      - snap
      - snapd
      - flatpak
      - gdm3
      - gnome-shell
    state: absent
    autoremove: true
    autoclean: true
    purge: true


- name: Adding desktop-environment
  ansible.builtin.apt:
    name:
      - i3-wm
      - xfonts-base
      - fonts-dejavu-core
      - i3status
      - i3lock
      - lightdm-gtk-greeter
      - lightdm-settings
    state: present
    install_recommends: false
  notify:
    - enable desktop

- name: Adding base packages
  ansible.builtin.apt:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - notification-daemon
      - rofi
      - yubioath-desktop
      - vim
      - xsettingsd
      - git
      - thunar
      - ffmpeg
      - openssh-client
      - seahorse
      - whois
      - firefox
      - mousepad
      - curl
      - apt-transport-https
      - feh
      - unattended-upgrades
      - gnome-terminal
      - pavucontrol
      - openvpn
      - qpdfview
      - atom
    state: present

- name: Installing picom for ubuntu 22.04
  ansible.builtin.apt:
    name:
      - picom
  when: ansible_facts['distribution_version'] == "22.04"

- name: Installing Virtualbox-Packages, if appropriate
  ansible.builtin.apt:
    name:
      - virtualbox-guest-x11
      - virtualbox-guest-utils
    state: present
  when: ansible_facts['virtualization_type'] == "virtualbox"
  notify: add user to vbox group
