---

pkgs_ubuntu_host: "{{ pkgs_vm_host }}"
pkgs_debian_host: "{{ pkgs_vm_host }}"
pkgs_ubuntu_guest: "{{ pkgs_vm_guest }}"
pkgs_debian_guest: "{{ pkgs_vm_guest }}"

pkgs_vm_guest:
  - apt-transport-https
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - gnome-terminal
  - yubioath-desktop
  - vim
  - git
  - openssh-client
  - seahorse
  - whois
  - firefox
  - ffmpeg
  - mousepad
  - curl
  - pavucontrol
  - openvpn
  - evince
  - atom
  - thunar
  - network-manager-gnome
  - network-manager-openvpn
  - network-manager
  - i3-wm
  - i3status
  - i3lock
  - lxappearance
  - adwaita-icon-theme-full
  - feh
  - rofi
  - flameshot

pkgs_vm_host:
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - vim
  - git
  - firefox
  - mousepad
  - curl
  - apt-transport-https
  - virtualbox

pkgs_kali_guest:
  - gobuster
  - ffuf
  - flameshot
