---
- name: Converge
  hosts: all
  become: true

  vars:
    upgrade_packages: false

  tasks:

    - name: Include base role
      ansible.builtin.include_role:
        name: base

    - name: Include admin role
      ansible.builtin.include_role:
        name: admin

    - name: Include harden role
      ansible.builtin.include_role:
        name: harden
