---

- name: Installing pip-packages
  ansible.builtin.pip:
    name:
      - yamllint
      - molecule
      - jedi
      - ipykernel
    state: latest

- name: Setting up jupyter notebook
  ansible.builtin.command:
    cmd: /usr/bin/python3 -m ipykernel install --user
  become: false
