---

- name: Updating apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Adding base packages
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present

- name: Install pip-packages
  ansible.builtin.pip:
    name:
      - mkdocs
      - mkdocs[i18n]
      - jedi
    state: latest
  become: false

- name: Update ipykernel
  ansible.builtin.pip:
    name:
      - ipykernel
    state: latest
  become: false
  notify: install ipykernel
