---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
  provision: true

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: ansible
  env:
    NO_UPGRADE: true

verifier:
  name: ansible
