---

- name: Hardening the mountpoints tmp and proc
  ansible.builtin.lineinfile:
    path: /etc/fstab
    create: false
    insertafter: EOF
    line: "proc    /proc    proc    defaults,nosuid,nodev,\
      noexec,relatime,hidepid=2     0     0"

- name: Checking for directories to restrict
  ansible.builtin.stat:
    path: "{{ restrict_dir_check }}"
  loop: "{{ restricted_directories }}"
  loop_control:
    loop_var: restrict_dir_check
  register: existing_restrict_dirs

- name: Restricting access to dirs
  ansible.builtin.file:
    path: "{{ restrict.stat.path }}"
    mode: "0700"
    owner: "root"
    group: "root"
  loop: "{{ existing_restrict_dirs.results|flatten }}"
  loop_control:
    loop_var: restrict
  when: restrict.stat.exists

- name: Restricting access to home directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}"
    mode: '0750'
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"

- name: Enabling the firefox-apparmor profile
  ansible.builtin.file:
    path: /etc/apparmor.d/disable/usr.bin.firefox
    state: absent
  notify: parse firefox apparmor profile

- name: Check if snap apparmor profile exists
  ansible.builtin.stat:
    path: /etc/apparmor.d/usr.lib.snapd.snap-confine.real
  register: snap_apparmor_profile

- name: Disabling the snap apparmor profile
  ansible.builtin.file:
    src: /etc/apparmor.d/usr.lib.snapd.snap-confine.real
    dest: /etc/apparmor.d/disable/usr.lib.snapd.snap-confine.real
    state: link
  when: snap_apparmor_profile.stat.exists
