---

- name: Hardening the mountpoints tmp and proc
  ansible.builtin.lineinfile:
    path: /etc/fstab
    create: false
    insertafter: EOF
    line: "{{ item }}"
  loop:
    - 'tmpfs  /tmp    tmpfs   rw,nodev,nosuid 0   0'

- name: Restricting access to important file and directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - path: "{{ ansible_facts['user_dir'] }}"
      mode: '0750'
      owner: "{{ ansible_facts['user_id'] }}"
      group: "{{ ansible_facts['user_id'] }}"
    - path: /usr/bin/as
      mode: '0770'
      owner: root
      group: root
    - path: /boot
      mode: '0700'
      owner: root
      group: root
    - path: /etc/iptables
      mode: '0700'
      owner: root
      group: root
    - path: /etc/arptables
      mode: '0700'
      owner: root
      group: root
  ignore_errors: true

- name: Enabling the firefox-apparmor profile
  ansible.builtin.file:
    path: /etc/apparmor.d/disable/usr.bin.firefox
    state: absent
  notify: parse firefox apparmor profile

- name: Check if snap apparmor profile exists
  ansible.builtin.stat:
    path: /etc/apparmor.d/usr.lib.snapd.snap-confine.real
  register: snap_apparmor_profile

- name: Disabling the snap apparmor profile
  ansible.builtin.file:
    src: /etc/apparmor.d/usr.lib.snapd.snap-confine.real
    dest: /etc/apparmor.d/disable/usr.lib.snapd.snap-confine.real
    state: link
  when: snap_apparmor_profile.stat.exists
