---
- include_tasks: "{{ item }}"
  loop:
    - packages.yaml
    - pam.yaml
    - file_actions.yaml
    - kernel.yaml

- name: Setting up firewall rules to default deny all incoming traffic
  community.general.ufw:
    state: enabled
    default: "{{ item.default }}"
    direction: "{{ item.direction }}"
  loop:
    - default: deny
      direction: incoming
    - default: deny
      direction: routed
    - default: allow
      direction: outgoing
