name: Install
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
      - name: Execute Ansible-Wrapper
        run: |
          ./install -d admin
        env:
          TERM: xterm-256color
          ANSIBLE_FORCE_COLOR: true
          PY_COLORS: '1'

      - name: Execute Openscap
        run: |
          sudo apt install -y libopenscap8
          wget https://github.com/ComplianceAsCode/content/releases/download/v0.1.65/scap-security-guide-0.1.65.zip
          unzip scap-security-guide-0.1.65.zip
          mkdir -p oscap_reports
          sudo oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_level2_workstation --report oscap_reports/oscap_cis_workstations_lvl2.html scap-security-guide-0.1.65/ssg-ubuntu2204-ds.xml || true
          sudo oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --report oscap_reports/oscap_basic.html scap-security-guide-0.1.65/ssg-ubuntu2204-ds.xml || true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OSCAP Reports
          path: oscap_reports/
          
