name: Install
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      #- name: Install dependencies
      #  run: python3 -m pip install -r $GITHUB_WORKSPACE/requirements.txt
      - name: Execute Ansible-Wrapper
        run: |
          ./install -d admin
          sudo apt install -y libopenscap8
          wget https://github.com/ComplianceAsCode/content/releases/download/v0.1.65/scap-security-guide-0.1.65.zip
          unzip scap-security-guide-0.1.65.zip
          mkdir oscap_reports
          sudo oscap xccdf eval --report oscap_reports/oscap_cis_workstations_lvl2.html --profile xccdf_org.ssgproject.content_profile_cis_level2_workstation ssg-ubuntu2204-ds.xml
          sudo oscap xccdf eval --report oscap_reports/oscap_basic.html --profile xccdf_org.ssgproject.content_profile_standard ssg-ubuntu2204-ds.xml
        env:
          TERM: xterm-256color
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OSCAP Reports
          path: oscap_reports
          
