name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        role: [kali,dev,admin]
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Check directory
        run: | 
          pwd
          ls -la
          echo $GITHUB_WORKSPACE
      #- name: Install dependencies
      #  run: python3 -m pip install -r ./ansible-setup/requirements.txt
      #- name: Test with molecule
      #  working-directory: ./ansible-setup/ansible/role/${{ matrix.role }}
      #  run: molecule test

