---
- name: Converge
  hosts: all

  vars:
    upgrade_packages: false

  tasks:
    - name: Include base role
      ansible.builtin.include_role:
        name: base
    - name: Include kali role
      ansible.builtin.include_role:
        name: kali
