---
- name: Converge
  hosts: all
  become: true

  vars:
    upgrade_pkgs: false

  tasks:
    - name: Include base role
      ansible.builtin.include_role:
        name: ../../../base
    - name: Include kali role
      ansible.builtin.include_role:
        name: kali
