---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: docker.io/kalilinux/kali-rolling
    dockerfile: ./molecule-kali.dockerfile
    pre_build_image: false

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: ansible

verifier:
  name: ansible
